//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalMpq.Explorer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrystalMpq.Explorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CrystalMpq Explorer.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot find another occurence of the text..
        /// </summary>
        internal static string CannotFindMoreMessage {
            get {
                return ResourceManager.GetString("CannotFindMoreMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ClosedFolderIcon {
            get {
                object obj = ResourceManager.GetObject("ClosedFolderIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CopyToolbarIcon {
            get {
                object obj = ResourceManager.GetObject("CopyToolbarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The directory &quot;{0}&quot; does not exists. Attempt to create it ?.
        /// </summary>
        internal static string DirectoryCreationDialogMessage {
            get {
                return ResourceManager.GetString("DirectoryCreationDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified directory does not exist.
        /// </summary>
        internal static string DirectoryCreationDialogTitle {
            get {
                return ResourceManager.GetString("DirectoryCreationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The directory &quot;{0}&quot; could not be created..
        /// </summary>
        internal static string DirectoryCreationErrorDialogMessage {
            get {
                return ResourceManager.GetString("DirectoryCreationErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error creating the directory.
        /// </summary>
        internal static string DirectoryCreationErrorDialogTitle {
            get {
                return ResourceManager.GetString("DirectoryCreationErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ExclamationToolbarIcon {
            get {
                object obj = ResourceManager.GetObject("ExclamationToolbarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExportToolbarIcon {
            get {
                object obj = ResourceManager.GetObject("ExportToolbarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extracting file {0} of {1}:
        ///{2}.
        /// </summary>
        internal static string ExtractionFileMessage {
            get {
                return ResourceManager.GetString("ExtractionFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} of {1} done..
        /// </summary>
        internal static string ExtractionStatusMessage {
            get {
                return ResourceManager.GetString("ExtractionStatusMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FindToolbarIcon {
            get {
                object obj = ResourceManager.GetObject("FindToolbarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid directory.
        /// </summary>
        internal static string InvalidDirectoryErrorDialogTitle {
            get {
                return ResourceManager.GetString("InvalidDirectoryErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified directory name contains invalid characters, such as &quot;, &lt;, &gt; or |..
        /// </summary>
        internal static string InvalidDirectoryNameErrorDialogMessage {
            get {
                return ResourceManager.GetString("InvalidDirectoryNameErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The directory name is empty..
        /// </summary>
        internal static string InvalidDirectoryNullErrorDialogMessage {
            get {
                return ResourceManager.GetString("InvalidDirectoryNullErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The directory name is too long..
        /// </summary>
        internal static string InvalidDirectoryPathTooLongErrorDialogMessage {
            get {
                return ResourceManager.GetString("InvalidDirectoryPathTooLongErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text not found..
        /// </summary>
        internal static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon OpenFolderIcon {
            get {
                object obj = ResourceManager.GetObject("OpenFolderIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenToolbarIcon {
            get {
                object obj = ResourceManager.GetObject("OpenToolbarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A file with the name &quot;{0}&quot; already exists in the directory &quot;{1}&quot;. Do you want to overwrite it ?.
        /// </summary>
        internal static string OverwriteFileDialogMessage {
            get {
                return ResourceManager.GetString("OverwriteFileDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Overwrite file.
        /// </summary>
        internal static string OverwriteFileDialogTitle {
            get {
                return ResourceManager.GetString("OverwriteFileDialogTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PropertiesToolbarIcon {
            get {
                object obj = ResourceManager.GetObject("PropertiesToolbarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encoding used by the text viewer when viewing a new file..
        /// </summary>
        internal static string PropertyDescriptionDefaultEncoding {
            get {
                return ResourceManager.GetString("PropertyDescriptionDefaultEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General Settings of CrystalMpq Explorer.
        /// </summary>
        internal static string PropertyDescriptionGeneralSettings {
            get {
                return ResourceManager.GetString("PropertyDescriptionGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The directory where plug-in assemblies are stored. Changes to this setting will be applied on next start..
        /// </summary>
        internal static string PropertyDescriptionPluginsDirectory {
            get {
                return ResourceManager.GetString("PropertyDescriptionPluginsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings of CrystalMpq&apos;s internal Text Viewer..
        /// </summary>
        internal static string PropertyDescriptionTextViewerSettings {
            get {
                return ResourceManager.GetString("PropertyDescriptionTextViewerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The background color of the view panel..
        /// </summary>
        internal static string PropertyDescriptionViewerBackColor {
            get {
                return ResourceManager.GetString("PropertyDescriptionViewerBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default Text Encoding.
        /// </summary>
        internal static string PropertyDisplayNameDefaultEncoding {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDefaultEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General Settings.
        /// </summary>
        internal static string PropertyDisplayNameGeneralSettings {
            get {
                return ResourceManager.GetString("PropertyDisplayNameGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plugins Directory.
        /// </summary>
        internal static string PropertyDisplayNamePluginsDirectory {
            get {
                return ResourceManager.GetString("PropertyDisplayNamePluginsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text Viewer Settings.
        /// </summary>
        internal static string PropertyDisplayNameTextViewerSettings {
            get {
                return ResourceManager.GetString("PropertyDisplayNameTextViewerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Background Color.
        /// </summary>
        internal static string PropertyDisplayNameViewerBackColor {
            get {
                return ResourceManager.GetString("PropertyDisplayNameViewerBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reached end of the text.Starting back at the beginning..
        /// </summary>
        internal static string ReachedEndMessage {
            get {
                return ResourceManager.GetString("ReachedEndMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SaveToolbarIcon {
            get {
                object obj = ResourceManager.GetObject("SaveToolbarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General.
        /// </summary>
        internal static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plug-ins.
        /// </summary>
        internal static string SettingsPlugins {
            get {
                return ResourceManager.GetString("SettingsPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 byte.
        /// </summary>
        internal static string UnitByteFormat {
            get {
                return ResourceManager.GetString("UnitByteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:0.##} bytes.
        /// </summary>
        internal static string UnitBytesFormat {
            get {
                return ResourceManager.GetString("UnitBytesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:0.##} EB.
        /// </summary>
        internal static string UnitExaByteFormat {
            get {
                return ResourceManager.GetString("UnitExaByteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:0.##} GB.
        /// </summary>
        internal static string UnitGigaByteFormat {
            get {
                return ResourceManager.GetString("UnitGigaByteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:0.##} KB.
        /// </summary>
        internal static string UnitKiloByteFormat {
            get {
                return ResourceManager.GetString("UnitKiloByteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:0.##} MB.
        /// </summary>
        internal static string UnitMegaByteFormat {
            get {
                return ResourceManager.GetString("UnitMegaByteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:0.##} PB.
        /// </summary>
        internal static string UnitPetaByteFormat {
            get {
                return ResourceManager.GetString("UnitPetaByteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:0.##} TB.
        /// </summary>
        internal static string UnitTeraByteFormat {
            get {
                return ResourceManager.GetString("UnitTeraByteFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon UnknownFileIcon {
            get {
                object obj = ResourceManager.GetObject("UnknownFileIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
