#region Copyright Notice
// This file is part of CrystalMPQ.
// 
// Copyright (C) 2007-2011 Fabien BARBIER
// 
// CrystalMPQ is licenced under the Microsoft Reciprocal License.
// You should find the licence included with the source of the program,
// or at this URL: http://www.microsoft.com/opensource/licenses.mspx#Ms-RL
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalMpq.Explorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.txt|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqExplorer, Version=1" +
            ".5.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.ini|CrystalMpq" +
            ".Explorer.Viewers.TextViewer, CrystalMpqExplorer, Version=1.5.0.0, Culture=neutr" +
            "al, PublicKeyToken=null</string>\r\n  <string>.wtf|CrystalMpq.Explorer.Viewers.Tex" +
            "tViewer, CrystalMpqExplorer, Version=1.5.0.0, Culture=neutral, PublicKeyToken=nu" +
            "ll</string>\r\n  <string>.sbt|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqEx" +
            "plorer, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n  <strin" +
            "g>.toc|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqExplorer, Version=1.5.0" +
            ".0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.css|CrystalMpq.Exp" +
            "lorer.Viewers.TextViewer, CrystalMpqExplorer, Version=1.5.0.0, Culture=neutral, " +
            "PublicKeyToken=null</string>\r\n  <string>.htm|CrystalMpq.Explorer.Viewers.TextVie" +
            "wer, CrystalMpqExplorer, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null</" +
            "string>\r\n  <string>.html|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqExplo" +
            "rer, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>." +
            "xml|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqExplorer, Version=1.5.0.0," +
            " Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.lua|CrystalMpq.Explor" +
            "er.Viewers.TextViewer, CrystalMpqExplorer, Version=1.5.0.0, Culture=neutral, Pub" +
            "licKeyToken=null</string>\r\n  <string>.js|CrystalMpq.Explorer.Viewers.TextViewer," +
            " CrystalMpqExplorer, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null</stri" +
            "ng>\r\n  <string>.xsl|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqExplorer, " +
            "Version=1.5.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.bmp|C" +
            "rystalMpq.Explorer.Viewers.BitmapViewer, CrystalMpqExplorer, Version=1.5.0.0, Cu" +
            "lture=neutral, PublicKeyToken=null</string>\r\n  <string>.jpg|CrystalMpq.Explorer." +
            "Viewers.BitmapViewer, CrystalMpqExplorer, Version=1.5.0.0, Culture=neutral, Publ" +
            "icKeyToken=null</string>\r\n  <string>.jpeg|CrystalMpq.Explorer.Viewers.BitmapView" +
            "er, CrystalMpqExplorer, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null</s" +
            "tring>\r\n  <string>.png|CrystalMpq.Explorer.Viewers.BitmapViewer, CrystalMpqExplo" +
            "rer, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>." +
            "gif|CrystalMpq.Explorer.Viewers.BitmapViewer, CrystalMpqExplorer, Version=1.5.0." +
            "0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.blp|CrystalMpq.Expl" +
            "orer.BaseViewers.BLPViewer, CrystalMpq.Explorer.BaseViewers, Version=1.2.0.0, Cu" +
            "lture=neutral, PublicKeyToken=null</string>\r\n  <string>.dbc|CrystalMpq.Explorer." +
            "BaseViewers.ClientDatabaseViewer, CrystalMpq.Explorer.BaseViewers, Version=1.2.0" +
            ".0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.wav|CrystalMpq.Exp" +
            "lorer.AudioVideo.MediaPlayer, CrystalMpq.Explorer.AudioVideo, Version=2.5.0.0, C" +
            "ulture=neutral, PublicKeyToken=null</string>\r\n  <string>.mp3|CrystalMpq.Explorer" +
            ".AudioVideo.MediaPlayer, CrystalMpq.Explorer.AudioVideo, Version=2.5.0.0, Cultur" +
            "e=neutral, PublicKeyToken=null</string>\r\n  <string>.avi|CrystalMpq.Explorer.Audi" +
            "oVideo.MediaPlayer, CrystalMpq.Explorer.AudioVideo, Version=2.5.0.0, Culture=neu" +
            "tral, PublicKeyToken=null</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ViewerAssociations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ViewerAssociations"]));
            }
            set {
                this["ViewerAssociations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SlateGray")]
        public global::System.Drawing.Color ViewerBackColor {
            get {
                return ((global::System.Drawing.Color)(this["ViewerBackColor"]));
            }
            set {
                this["ViewerBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("utf-8")]
        public string TextViewerDefaultEncoding {
            get {
                return ((string)(this["TextViewerDefaultEncoding"]));
            }
            set {
                this["TextViewerDefaultEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plugins")]
        public string PluginsDirectory {
            get {
                return ((string)(this["PluginsDirectory"]));
            }
            set {
                this["PluginsDirectory"] = value;
            }
        }
    }
}
